### ISSUE TITLE
Dependent device delete sometimes does not work

### ISSUE THREAD

**Issue by josephroberts** [resin-io/edge-node-manager#56]
Dependent device delete occasionally results in:
```
27.10.16 12:56:48 [+0100] 2016/10/27 11:56:48 http: panic serving 127.0.0.1:44926: runtime error: invalid memory address or nil pointer dereference
27.10.16 12:56:48 [+0100] goroutine 148 [running]:
27.10.16 12:56:48 [+0100] net/http.(*conn).serve.func1(0x10832840)
27.10.16 12:56:48 [+0100] /usr/local/go/src/net/http/server.go:1491 +0x9c
27.10.16 12:56:48 [+0100] panic(0x324170, 0x1070c010)
27.10.16 12:56:48 [+0100] /usr/local/go/src/runtime/panic.go:458 +0x454
27.10.16 12:56:48 [+0100] github.com/resin-io/edge-node-manager/api.DependantDeviceDelete(0x483cf8, 0x10805ef0, 0x10766d00)
27.10.16 12:56:48 [+0100] /go/src/github.com/resin-io/edge-node-manager/api/handlers.go:71 +0x224
27.10.16 12:56:48 [+0100] net/http.HandlerFunc.ServeHTTP(0x39c240, 0x483cf8, 0x10805ef0, 0x10766d00)
27.10.16 12:56:48 [+0100] /usr/local/go/src/net/http/server.go:1726 +0x34
27.10.16 12:56:48 [+0100] github.com/resin-io/edge-node-manager/api.Logger.func1(0x483cf8, 0x10805ef0, 0x10766d00)
27.10.16 12:56:48 [+0100] /go/src/github.com/resin-io/edge-node-manager/api/logger.go:15 +0x88
27.10.16 12:56:48 [+0100] net/http.HandlerFunc.ServeHTTP(0x10712500, 0x483cf8, 0x10805ef0, 0x10766d00)
27.10.16 12:56:48 [+0100] /usr/local/go/src/net/http/server.go:1726 +0x34
27.10.16 12:56:48 [+0100] github.com/resin-io/edge-node-manager/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0x10716150, 0x483cf8, 0x10805ef0, 0x10766d00)
27.10.16 12:56:48 [+0100] /go/src/github.com/resin-io/edge-node-manager/vendor/github.com/gorilla/mux/mux.go:107 +0x240
27.10.16 12:56:48 [+0100] net/http.serverHandler.ServeHTTP(0x10718640, 0x483cf8, 0x10805ef0, 0x1083c200)
27.10.16 12:56:48 [+0100] /usr/local/go/src/net/http/server.go:2202 +0x150
27.10.16 12:56:48 [+0100] net/http.(*conn).serve(0x10832840, 0x4843f0, 0x10836880)
27.10.16 12:56:48 [+0100] /usr/local/go/src/net/http/server.go:1579 +0xde8
27.10.16 12:56:48 [+0100] created by net/http.(*Server).Serve
27.10.16 12:56:48 [+0100] /usr/local/go/src/net/http/server.go:2293 +0x470
```

**Comment by josephroberts** [comment]
also
```
27.10.16 14:49:01 [+0100] INFO[0084] Device deleted name=wandering-dust
27.10.16 14:49:01 [+0100] panic: runtime error: invalid memory address or nil pointer dereference
27.10.16 14:49:01 [+0100] [signal SIGSEGV: segmentation violation code=0x1 addr=0x64 pc=0xf2f20]
27.10.16 14:49:01 [+0100]
27.10.16 14:49:01 [+0100] goroutine 1 [running]:
27.10.16 14:49:01 [+0100] panic(0x325180, 0x1070c010)
27.10.16 14:49:01 [+0100] /usr/local/go/src/runtime/panic.go:500 +0x33c
27.10.16 14:49:01 [+0100] github.com/resin-io/edge-node-manager/application.(*Application).handleRestartFlag(0x107e01e0, 0x0, 0x0)
27.10.16 14:49:01 [+0100] /go/src/github.com/resin-io/edge-node-manager/application/application.go:334 +0xbc
27.10.16 14:49:01 [+0100] github.com/resin-io/edge-node-manager/application.(*Application).HandleFlags(0x107e01e0, 0x0, 0x0)
27.10.16 14:49:01 [+0100] /go/src/github.com/resin-io/edge-node-manager/application/application.go:241 +0x58
27.10.16 14:49:01 [+0100] github.com/resin-io/edge-node-manager/process.Run(0x107e01e0, 0x0, 0x0, 0x0)
27.10.16 14:49:01 [+0100] /go/src/github.com/resin-io/edge-node-manager/process/process.go:61 +0x5a0
27.10.16 14:49:01 [+0100] main.main()
27.10.16 14:49:01 [+0100] /go/src/github.com/resin-io/edge-node-manager/main.go:35 +0x304
```
